language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'

install:
  - composer install

before_script:
  - printf "\n" | pecl install imagick-3.3.0
  - echo "extension=imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - phpunit --verbose
